spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/tacomall?serverTimezone=Asia/Shanghai
          username: root
          password: root
  boot:
    admin:
      client:
        url: http://localhost:7030
        username: root
        password: 123456
        instance:
          prefer-ip: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      instance-id: ${spring.application.name}:${random.value}
