spring:
  boot:
    admin:
      client:
        url: http://localhost:7030
        password: root
        username: 123456
        instance:
          prefer-ip: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    prefer-ip-address: true