spring:
  boot:
    admin:
      client:
        url: http://localhost:7030
        password: root
        username: 123456
        instance:
          prefer-ip: true
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url:
          username:
          password:


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    prefer-ip-address: true
oss:
  endPoint: 
  accesskey: 
  accessSecret: 
  bucket: 
  expire: 3600
  callback: 
