server:
  port: 8002
spring:
  application:
    name: service-biz-file
  profiles:
    active: @environment@
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug
mybatis-plus:
  type-aliases-package: cn.codingtalk.tacomallservicebizfile
  mapper-locations: classpath:/mapper/**/*Mapper.xml
