server:
  port: 7030

spring:
  application:
    name: admin
  profiles:
    active: @environment@
  security:
    user:
      name: root
      password: 123456

eureka:
  instance:
    metadata-map:
      "user.name": ${spring.security.user.name}
      "user.password": ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS