server:
  port: 9000
spring:
  application:
    name: api-portal
  profiles:
    active: @environment@
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
mybatis-plus:
  type-aliases-package: cn.codingtalk.tacomallapiportal
  mapper-locations: classpath:/mapper/*Mapper.xml
wx:
  miniapp:
      appid: wx1492e33a9a6b64a3